### ISSUE TITLE
authGetAccessTokenGet

### ISSUE THREAD

**Issue by valerii-efimov** [voximplant/php-smartcalls-sdk#1]
Hello 
i try 
` $result = $apiInstance->authGetAccessTokenGet($domain, $username, $password);`

but get this result:
![image](https://user-images.githubusercontent.com/5989188/61793391-b713da80-ae27-11e9-9653-fa24b6b5282e.png)
when i go to  `public static function deserialize($data, $class, $httpHeaders = null)` in `class ObjectSerializer` end `var_dump($data)` get:

![image](https://user-images.githubusercontent.com/5989188/61793508-f9d5b280-ae27-11e9-80c9-02a6993ac97b.png)

Am I doing something wrong?

**Comment by DmitryIvaneychik** [comment]
Hi, to get the result, properly use the method getResult(), 
`$result->getResult()`

**Comment by valerii-efimov** [comment]
Thank you very much.
