### ISSUE TITLE
Class 'BigDecimal' not found

### ISSUE THREAD

**Issue by baster20** [voximplant/php-smartcalls-sdk#2]
When use ```callsSearchCallsGet``` method in ```Smartcalls\client\CallsApi``` class and receive result , on this file ```vendor/voximplant/php-smartcalls-sdk/lib/ObjectSerializer.php on line 298```
throw fatal error ```Class 'BigDecimal' not found```.
Perhaps this is due to https://github.com/swagger-api/swagger-codegen-generators/pull/245.
In ```vendor/voximplant/php-smartcalls-sdk/lib/Model/CallsType.php on line 70```
use ```'call_cost' => 'BigDecimal'```. Need change to ```float```

Stack:
> PHP Fatal error:  Class 'BigDecimal' not found in /var/www/html/vendor/voximplant/php-smartcalls-sdk/lib/ObjectSerializer.php on line 298
PHP Stack trace:
PHP   1. {main}() /var/www/html/artisan:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/html/artisan:59
PHP   3. Symfony\Component\Console\Application->doRun() /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:121
PHP   4. Symfony\Component\Console\Application->doRunCommand() /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:191
PHP   5. Illuminate\Console\Command->run() /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:887
PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:96
PHP   7. Illuminate\Console\Command->execute() /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
PHP   8. GetCargoUserAndCall->fire() /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:108
PHP   9. GetCargoUserAndCall->isNeedCallByCallsHistory() /var/www/html/app/commands/GetCargoUserAndCall.php:151
PHP  10. Smartcalls->getCallsByHistory() /var/www/html/app/commands/GetCargoUserAndCall.php:515
PHP  11. Smartcalls\client\CallsApi->callsSearchCallsGet() /var/www/html/app/libs/Smartcalls.php:165
PHP  12. Smartcalls\client\CallsApi->callsSearchCallsGetWithHttpInfo() /var/www/html/vendor/voximplant/php-smartcalls-sdk/lib/client/CallsApi.php:932
PHP  13. Smartcalls\ObjectSerializer::deserialize() /var/www/html/vendor/voximplant/php-smartcalls-sdk/lib/client/CallsApi.php:993
PHP  14. Smartcalls\ObjectSerializer::deserialize() /var/www/html/vendor/voximplant/php-smartcalls-sdk/lib/ObjectSerializer.php:315
PHP  15. Smartcalls\ObjectSerializer::deserialize() /var/www/html/vendor/voximplant/php-smartcalls-sdk/lib/ObjectSerializer.php:246
PHP  16. Smartcalls\ObjectSerializer::deserialize() /var/www/html/vendor/voximplant/php-smartcalls-sdk/lib/ObjectSerializer.php:315

**Comment by DmitryIvaneychik** [comment]
Hello! We fixed this in the last commit. Try it now.

**Comment by baster20** [comment]
Спасибо за оперативность )
